[package]
name = "actix_http"
version = "0.1.0"
authors = ["devin <andy129408@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "1.0.9"